"""Tests for Score placement API: `add(at=)`, `add(after=)`, `add(before=)`,
`append`, `prepend`, plus validation of mutual exclusivity, name collisions,
and unknown-target references."""

import pytest

from klotho.chronos import TemporalUnit as UT
from klotho.thetos import CompositionalUnit as UC
from klotho.thetos.composition.score import Score, ScoreItem


def _uc(dur_beats=4, bpm=60):
    return UC(tempus='4/4', prolatio=(1,) * dur_beats, beat='1/4', bpm=bpm)


class TestAddPlacement:
    def test_default_placement_is_zero(self):
        s = Score()
        item = s.add(_uc(), name='a')
        assert item.start == 0.0

    def test_at_float(self):
        s = Score()
        item = s.add(_uc(), name='a', at=3.5)
        assert item.start == pytest.approx(3.5)

    def test_at_string_matches_item_start(self):
        s = Score()
        s.add(_uc(), name='a', at=2.0)
        item = s.add(_uc(), name='b', at='a')
        assert item.start == s['a'].start == 2.0

    def test_after(self):
        s = Score()
        s.add(_uc(), name='a')
        a_end = s['a'].end
        item = s.add(_uc(), name='b', after='a')
        assert item.start == pytest.approx(a_end)

    def test_before(self):
        s = Score()
        s.add(_uc(), name='anchor', at=5.0)
        item = s.add(_uc(), name='pre', before='anchor')
        assert item.end == pytest.approx(5.0)
        assert item.start == pytest.approx(5.0 - item.duration)

    def test_returns_score_item(self):
        s = Score()
        item = s.add(_uc(), name='a')
        assert isinstance(item, ScoreItem)
        assert item.name == 'a'


class TestAddValidation:
    def test_mutual_exclusion_raises(self):
        s = Score()
        s.add(_uc(), name='a')
        with pytest.raises(ValueError, match="at most one"):
            s.add(_uc(), name='b', at=1.0, after='a')

    def test_unknown_after_raises(self):
        s = Score()
        with pytest.raises(KeyError, match="ghost"):
            s.add(_uc(), name='a', after='ghost')

    def test_unknown_before_raises(self):
        s = Score()
        with pytest.raises(KeyError, match="ghost"):
            s.add(_uc(), name='a', before='ghost')

    def test_unknown_at_string_raises(self):
        s = Score()
        with pytest.raises(KeyError, match="ghost"):
            s.add(_uc(), name='a', at='ghost')

    def test_duplicate_name_raises(self):
        s = Score()
        s.add(_uc(), name='a')
        with pytest.raises(ValueError, match="already exists"):
            s.add(_uc(), name='a')

    def test_unregistered_track_raises(self):
        s = Score()
        with pytest.raises(ValueError, match="not registered"):
            s.add(_uc(), name='a', track='unknown_track')

    def test_registered_track_accepted(self):
        s = Score().track('melody')
        item = s.add(_uc(), name='a', track='melody')
        assert item.track == 'melody'

    def test_main_track_is_implicit(self):
        s = Score()
        item = s.add(_uc(), name='a', track='main')
        assert item.track == 'main'


class TestAutoGeneratedNames:
    def test_auto_name_increments(self):
        s = Score()
        a = s.add(_uc())
        b = s.add(_uc())
        assert a.name == 'item_0'
        assert b.name == 'item_1'


class TestAppendPrepend:
    def test_append_to_empty(self):
        s = Score()
        item = s.append(_uc(), name='a')
        assert item.start == 0.0

    def test_append_after_latest_end(self):
        s = Score()
        s.add(_uc(), name='a', at=10.0)
        item = s.append(_uc(), name='b')
        assert item.start == pytest.approx(s['a'].end)

    def test_prepend_to_empty(self):
        s = Score()
        item = s.prepend(_uc(), name='a')
        assert item.start == 0.0

    def test_prepend_shifts_existing_items(self):
        s = Score()
        s.add(_uc(), name='a', at=0.0)
        s.add(_uc(), name='b', after='a')
        new_uc = _uc(dur_beats=2)
        new_item = s.prepend(new_uc, name='pre')
        assert new_item.start == 0.0
        assert s['a'].start == pytest.approx(new_item.duration)
        assert s['b'].start == pytest.approx(new_item.duration + s['a'].duration)

    def test_prepend_places_new_item_at_front(self):
        s = Score()
        s.add(_uc(), name='a')
        s.prepend(_uc(), name='pre')
        assert s.names() == ['pre', 'a']
