from enum import Enum, EnumMeta

class DirectValueEnumMeta(EnumMeta):
    def __getattribute__(cls, name):
        member = super().__getattribute__(name)
        if isinstance(member, cls):
            return member.value
        return member

# ------------------------------------------------------------------------------------
# ANCIENT GREEK SYMBOLS
# ------------------------------------------------------------------------------------
class AncientGreek(Enum, metaclass=DirectValueEnumMeta):
    '''
    Enum for Ancient Greek alphabet and symbols.
    
    
    '''
    # Uppercase Greek Letters
    ALPHA_UPPER         = 'Α'
    BETA_UPPER          = 'Β'
    GAMMA_UPPER         = 'Γ'
    DELTA_UPPER         = 'Δ'
    EPSILON_UPPER       = 'Ε'
    ZETA_UPPER          = 'Ζ'
    ETA_UPPER           = 'Η'
    THETA_UPPER         = 'Θ'
    IOTA_UPPER          = 'Ι'
    KAPPA_UPPER         = 'Κ'
    LAMBDA_UPPER        = 'Λ'
    MU_UPPER            = 'Μ'
    NU_UPPER            = 'Ν'
    XI_UPPER            = 'Ξ'
    OMICRON_UPPER       = 'Ο'
    PI_UPPER            = 'Π'
    RHO_UPPER           = 'Ρ'
    SIGMA_UPPER         = 'Σ'
    TAU_UPPER           = 'Τ'
    UPSILON_UPPER       = 'Υ'
    PHI_UPPER           = 'Φ'
    CHI_UPPER           = 'Χ'
    PSI_UPPER           = 'Ψ'
    OMEGA_UPPER         = 'Ω'

    # Lowercase Greek Letters
    ALPHA_LOWER         = 'α'
    BETA_LOWER          = 'β'
    GAMMA_LOWER         = 'γ'
    DELTA_LOWER         = 'δ'
    EPSILON_LOWER       = 'ε'
    ZETA_LOWER          = 'ζ'
    ETA_LOWER           = 'η'
    THETA_LOWER         = 'θ'
    IOTA_LOWER          = 'ι'
    KAPPA_LOWER         = 'κ'
    LAMBDA_LOWER        = 'λ'
    MU_LOWER            = 'μ'
    NU_LOWER            = 'ν'
    XI_LOWER            = 'ξ'
    OMICRON_LOWER       = 'ο'
    PI_LOWER            = 'π'
    RHO_LOWER           = 'ρ'
    SIGMA_LOWER_FINAL   = 'ς'  # Final sigma
    SIGMA_LOWER         = 'σ'
    TAU_LOWER           = 'τ'
    UPSILON_LOWER       = 'υ'
    PHI_LOWER           = 'φ'
    CHI_LOWER           = 'χ'
    PSI_LOWER           = 'ψ'
    OMEGA_LOWER         = 'ω'

    # Miscellaneous Greek Symbols
    THETA_SYMBOL        = 'ϑ'
    PHI_SYMBOL          = 'ϕ'
    PI_SYMBOL           = 'ϖ'
    KAI_SYMBOL          = 'ϗ'
    SAMPI               = 'Ϡ'

# ------------------------------------------------------------------------------------
# RUNIC SYMBOLS
# ------------------------------------------------------------------------------------
class RUNIC(Enum, metaclass=DirectValueEnumMeta):
    '''
    Runic symbols.
    
    '''
    class OLD_NORSE(Enum, metaclass=DirectValueEnumMeta):
        '''
        Old Norse runeic scripts.
        
        '''
        class Elder_Futhark(Enum, metaclass=DirectValueEnumMeta):
            FEHU      = 'ᚠ'
            URUZ      = 'ᚢ'
            THURISAZ  = 'ᚦ'
            ANSUZ     = 'ᚨ'
            RAIDHO    = 'ᚱ'
            KENAZ     = 'ᚲ'
            GEBO      = 'ᚷ'
            WUNJO     = 'ᚹ'
            HAGALAZ   = 'ᚺ'
            NAUDIZ    = 'ᚾ'
            ISA       = 'ᛁ'
            JERA      = 'ᛃ'
            EIHWAZ    = 'ᛇ'
            PERTHRO   = 'ᛈ'
            ALGIZ     = 'ᛉ'
            SOWILO    = 'ᛊ'
            TIWAZ     = 'ᛏ'
            BERKANO   = 'ᛒ'
            EHWAZ     = 'ᛖ'
            MANNAZ    = 'ᛗ'
            LAGUZ     = 'ᛚ'
            INGWAZ    = 'ᛜ'
            DAGAZ     = 'ᛞ'
            OTHALA    = 'ᛟ'
        class Younger_Futhark(Enum, metaclass=DirectValueEnumMeta):
            FE        = 'ᚠ'
            UR        = 'ᚢ'
            THURS     = 'ᚦ'
            AS        = 'ᚬ'
            REID      = 'ᚱ'
            KAUN      = 'ᚴ'
            HAGALL    = 'ᚼ'
            NAUDR     = 'ᚾ'
            IS        = 'ᛁ'
            AR        = 'ᛅ'
            SOL       = 'ᛋ'
            TIU       = 'ᛐ'
            BJARKAN   = 'ᛒ'
            MADHR     = 'ᛘ'
            LOGR      = 'ᛚ'
            YR        = 'ᛦ'
        class Anglo_Saxon_Futhorc(Enum, metaclass=DirectValueEnumMeta):
            FEH       = 'ᚠ'
            UR        = 'ᚢ'
            THORN     = 'ᚦ'
            OS        = 'ᚩ'
            RAD       = 'ᚱ'
            CEN       = 'ᚳ'
            GYFU      = 'ᚷ'
            WYNN      = 'ᚹ'
            HAEGEL    = 'ᚻ'
            NYD       = 'ᚾ'
            IS        = 'ᛁ'
            GER       = 'ᛄ'
            EO        = 'ᛇ'
            PEORD     = 'ᛈ'
            EOLH      = 'ᛉ'
            SIGEL     = 'ᛋ'
            TIW       = 'ᛏ'
            BEORC     = 'ᛒ'
            EH        = 'ᛖ'
            MANN      = 'ᛗ'
            LAGU      = 'ᛚ'
            ING       = 'ᛝ'
            DAEG      = 'ᛞ'
            ODAL      = 'ᛟ'
            AESC      = 'ᚫ'

        # ELDER_FUTHARK       = Elder_Futhark
        # YOUNGER_FUTHARK     = Younger_Futhark
        # ANGLO_SAXON_FUTHORC = Anglo_Saxon_Futhorc


# ------------------------------------------------------------------------------------
# CUNEIFORM SYMBOLS
# ------------------------------------------------------------------------------------

class CUNEIFORM(Enum, metaclass=DirectValueEnumMeta):
    '''
    Cuneiform symbols.
    
    '''
    class Sumerian(Enum, metaclass=DirectValueEnumMeta):
        '''
        Enum for Sumerian Cuneiform symbols.
        
        '''
        A               = '𒀀'
        AB              = '𒀊'
        AD              = '𒀜'
        AG              = '𒀝'
        AK              = '𒀭'
        AL              = '𒀸'
        AM              = '𒄠'
        AN              = '𒀭'
        AR              = '𒅈'
        ASH             = '𒀸'
        BA              = '𒁀'
        BAD             = '𒁁'
        BAR             = '𒁉'
        BI              = '𒁍'
        BU              = '𒁲'
        DA              = '𒁕'
        DAG             = '𒁕'
        DI              = '𒁺'
        DU              = '𒁺'
        E               = '𒂊'
        EN              = '𒂗'
        ER              = '𒂗'
        GA              = '𒂵'
        GAN             = '𒃲'
        GAR             = '𒃲'
        GI              = '𒄀'
        GID             = '𒄄'
        GIN             = '𒄄'
        GIR             = '𒄑'
        GISH            = '𒄑'
        GU              = '𒄖'
        GUD             = '𒄖'
        GUL             = '𒄖'
        HA              = '𒄩'
        HI              = '𒄭'
        HU              = '𒄷'
        I               = '𒅆'
        IB              = '𒅋'
        ID              = '𒅖'
        IM              = '𒅴'
        IN              = '𒅷'
        IR              = '𒅹'
        ISH             = '𒅻'
        KA              = '𒆠'
        KAK             = '𒆤'
        KI              = '𒆠'
        KU              = '𒆪'
        KUG             = '𒆬'
        KUR             = '𒆳'
        LAGAB           = '𒆸'
        LAGAR           = '𒆹'
        LAM             = '𒆷'
        LI              = '𒇷'
        LU              = '𒇻'
        LUM             = '𒇽'
        MA              = '𒌝'
        MASH            = '𒌝'
        ME              = '𒌝'
        MIN             = '𒌞'
        MU              = '𒌦'
        MUG             = '𒌧'
        MUNUS           = '𒌨'
        NA              = '𒈾'
        NE              = '𒉈'
        NIM             = '𒉌'
        NU              = '𒉡'
        PA              = '𒉺'
        PAD             = '𒉼'
        PAN             = '𒉽'
        PAP             = '𒉿'
        PI              = '𒊊'
        QA              = '𒋀'
        QI              = '𒋗'
        RA              = '𒊏'
        RI              = '𒊑'
        RU              = '𒊒'
        SA              = '𒊓'
        SAG             = '𒊕'
        SAL             = '𒊖'
        SAN             = '𒊗'
        SAR             = '𒊘'
        SHAR            = '𒊭'
        SHE             = '𒊺'
        SHU             = '𒋗'
        SI              = '𒋚'
        SIG             = '𒋛'
        SIGA            = '𒋜'
        SU              = '𒋢'
        SUD             = '𒋤'
        TA              = '𒋫'
        TAG             = '𒋬'
        TAR             = '𒋰'
        TE              = '𒋼'
        TI              = '𒋾'
        TIL             = '𒌁'
        TU              = '𒌅'
        TUM             = '𒌇'
        TUR             = '𒌉'
        U               = '𒌋'
        UD              = '𒌑'
        UM              = '𒌓'
        UN              = '𒌖'
        UR              = '𒌝'
        URU             = '𒌨'
        US              = '𒌫'
        UT              = '𒌰'
        UTU             = '𒌱'
        UZU             = '𒍑'
        ZA              = '𒍝'
        ZAG             = '𒍠'
        ZU              = '𒍪'
    class Akkadian(Enum, metaclass=DirectValueEnumMeta):
        '''
        Enum for Akkadian Cuneiform symbols.
        '''
        A               = '𒀀'
        AB              = '𒀊'
        AD              = '𒀜'
        AG              = '𒀝'
        AK              = '𒀭'
        AL              = '𒀸'
        AM              = '𒄠'
        AN              = '𒀭'
        AR              = '𒅈'
        ASH             = '𒀸'
        BA              = '𒁀'
        BAD             = '𒁁'
        BAR             = '𒁉'
        BI              = '𒁍'
        BU              = '𒁲'
        DA              = '𒁕'
        DAG             = '𒁕'
        DI              = '𒁺'
        DU              = '𒁺'
        E               = '𒂊'
        EN              = '𒂗'
        ER              = '𒂗'
        GA              = '𒂵'
        GAN             = '𒃲'
        GAR             = '𒃲'
        GI              = '𒄀'
        GID             = '𒄄'
        GIN             = '𒄄'
        GIR             = '𒄑'
        GISH            = '𒄑'
        GU              = '𒄖'
        GUD             = '𒄖'
        GUL             = '𒄖'
        HA              = '𒄩'
        HI              = '𒄭'
        HU              = '𒄷'
        I               = '𒅆'
        IB              = '𒅋'
        ID              = '𒅖'
        IM              = '𒅴'
        IN              = '𒅷'
        IR              = '𒅹'
        ISH             = '𒅻'
        KA              = '𒆠'
        KAK             = '𒆤'
        KI              = '𒆠'
        KU              = '𒆪'
        KUG             = '𒆬'
        KUR             = '𒆳'
        LAGAB           = '𒆸'
        LAGAR           = '𒆹'
        LAM             = '𒆷'
        LI              = '𒇷'
        LU              = '𒇻'
        LUM             = '𒇽'
        MA              = '𒌝'
        MASH            = '𒌝'
        ME              = '𒌝'
        MIN             = '𒌞'
        MU              = '𒌦'
        MUG             = '𒌧'
        MUNUS           = '𒌨'
        NA              = '𒈾'
        NE              = '𒉈'
        NIM             = '𒉌'
        NU              = '𒉡'
        PA              = '𒉺'
        PAD             = '𒉼'
        PAN             = '𒉽'
        PAP             = '𒉿'
        PI              = '𒊊'
        QA              = '𒋀'
        QI              = '𒋗'
        RA              = '𒊏'
        RI              = '𒊑'
        RU              = '𒊒'
        SA              = '𒊓'
        SAG             = '𒊕'
        SAL             = '𒊖'
        SAN             = '𒊗'
        SAR             = '𒊘'
        SHAR            = '𒊭'
        SHE             = '𒊺'
        SHU             = '𒋗'
        SI              = '𒋚'
        SIG             = '𒋛'
        SIGA            = '𒋜'
        SU              = '𒋢'
        SUD             = '𒋤'
        TA              = '𒋫'
        TAG             = '𒋬'
        TAR             = '𒋰'
        TE              = '𒋼'
        TI              = '𒋾'
        TIL             = '𒌁'
        TU              = '𒌅'
        TUM             = '𒌇'
        TUR             = '𒌉'
        U               = '𒌋'
        UD              = '𒌑'
        UM              = '𒌓'
        UN              = '𒌖'
        UR              = '𒌝'
        URU             = '𒌨'
        US              = '𒌫'
        UT              = '𒌰'
        UTU             = '𒌱'
        UZU             = '𒍑'
        ZA              = '𒍝'
        ZAG             = '𒍠'
        ZU              = '𒍪'

    SUMERIAN = Sumerian
    AKKADIAN = Akkadian

# ------------------------------------------------------------------------------------
# MATH SYMBOLS
# ------------------------------------------------------------------------------------
class Mathematical(Enum, metaclass=DirectValueEnumMeta):
    '''
    Enum for various mathematical symbols and their Unicode representations.
    
    '''
    # Mathematical Symbols
    INCREMENT                      = '∆'
    INFINITE                       = '∞'  # Changed from INFINITY
    PARTIAL_DIFFERENTIAL           = '∂'
    NABLA                          = '∇'
    ELEMENT_OF                     = '∈'
    NOT_ELEMENT_OF                 = '∉'  # Changed from NOT_AN_ELEMENT_OF
    SMALL_ELEMENT                  = '∊'  # Changed from SMALL_ELEMENT_OF
    CONTAINS_MEMBER                = '∋'  # Changed from CONTAINS_AS_MEMBER
    NOT_CONTAINS_MEMBER            = '∌'  # Changed from DOES_NOT_CONTAIN_AS_MEMBER
    N_ARY_PRODUCT                  = '∏'
    N_ARY_COPRODUCT                = '∐'
    N_ARY_SUMMATION                = '∑'
    MINUS_SIGN                     = '−'
    MINUS_OR_PLUS                  = '∓'  # Changed from MINUS_OR_PLUS_SIGN
    DOT_PLUS                       = '∔'
    DIVISION_SLASH                 = '∕'
    SET_MINUS                      = '∖'
    ASTERISK_OPERATOR              = '∗'
    RING_OPERATOR                  = '∘'
    BULLET_OPERATOR                = '∙'
    SQUARE_ROOT                    = '√'
    CUBE_ROOT                      = '∛'
    FOURTH_ROOT                    = '∜'
    CONSEQUENTLY                   = '∴'  # Changed from THEREFORE
    BECAUSE_OF                     = '∵'  # Changed from BECAUSE
    PROPORTIONAL_TO                = '∝'
    RIGHT_ANGLE                    = '∟'
    ANGLE                          = '∠'
    MEASURED_ANGLE                 = '∡'
    SPHERICAL_ANGLE                = '∢'
    DIVIDES                        = '∣'
    DOES_NOT_DIVIDE                = '∤'
    PARALLEL_TO                    = '∥'
    NOT_PARALLEL_TO                = '∦'
    LOGICAL_AND                    = '∧'
    LOGICAL_OR                     = '∨'
    INTERSECTION                   = '∩'
    UNION                          = '∪'
    INTEGRAL                       = '∫'
    DOUBLE_INTEGRAL                = '∬'
    TRIPLE_INTEGRAL                = '∭'
    CONTOUR_INTEGRAL               = '∮'
    SURFACE_INTEGRAL               = '∯'
    VOLUME_INTEGRAL                = '∰'
    CLOCKWISE_INTEGRAL             = '∱'
    CLOCKWISE_CONTOUR_INTEGRAL     = '∲'
    ANTICLOCKWISE_CONTOUR_INTEGRAL = '∳'

# ------------------------------------------------------------------------------------
# LOGICAL SYMBOLS
# ------------------------------------------------------------------------------------